// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj_rjEkwXi1aOHIYVOnS5LS5ni1bWxcFg',
    appId: '1:1048454456889:android:95046d572bbd2905b44fe8',
    messagingSenderId: '1048454456889',
    projectId: 'msd-wallet',
    databaseURL: 'https://msd-wallet-default-rtdb.firebaseio.com',
    storageBucket: 'msd-wallet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZI1u9bswaEC0d-xnioAgK8xPCzWGk_l8',
    appId: '1:1048454456889:ios:131d0a325a6bc0aeb44fe8',
    messagingSenderId: '1048454456889',
    projectId: 'msd-wallet',
    databaseURL: 'https://msd-wallet-default-rtdb.firebaseio.com',
    storageBucket: 'msd-wallet.appspot.com',
    iosClientId: '1048454456889-tsr33dhumcqc3o01d9a83busm7km0bjq.apps.googleusercontent.com',
    iosBundleId: 'bharath.thirunahari.mobileWalletApp',
  );
}
